/*
  Warnings:

  - The values [HEALTH_AND_WELLNESS] on the enum `CategoryEnum` will be removed. If these variants are still used in the database, this will fail.
  - The values [POLITICAL_PARTIES,GOVERNMENT_POLICIES,CORRUPTION,JOBS_AND_EMPLOYMENT,ECONOMIC_POLICIES,INCOME_INEQUALITY,TRADE_AND_COMMERCE,TAXATION,CRIME_AND_PUNISHMENT,LEGAL_REFORMS,JUSTICE_SYSTEM,POLICING,CYBERCRIME,HIGHER_EDUCATION,ONLINE_LEARNING,EDUCATION_POLICIES,STUDENT_WELFARE,POLLUTION,WILDLIFE_CONSERVATION,WASTE_MANAGEMENT,CASTE_SYSTEM,GENDER_EQUALITY,MINORITY_RIGHTS,POVERTY,LGBTQ_PLUS_RIGHTS,PUBLIC_HEALTH,MENTAL_HEALTH,HEALTHCARE_ACCESS,NUTRITION,DISEASE_PREVENTION,MEDICAL_ETHICS,ARTIFICIAL_INTELLIGENCE,SPACE_EXPLORATION,MEDICAL_SCIENCE,INFORMATION_TECHNOLOGY,ENVIRONMENTAL_TECH,HOLLYWOOD,BOLLYWOOD,TV_SHOWS,GAMING,SOCIAL_MEDIA,CENSORSHIP,HOCKEY,MOTORSPORTS] on the enum `InterestEnum` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "CategoryEnum_new" AS ENUM ('POLITICS_AND_GOVERNANCE', 'ECONOMY_AND_DEVELOPMENT', 'LAW_AND_JUSTICE', 'EDUCATION', 'ENVIRONMENT_AND_SUSTAINABILITY', 'SOCIAL_ISSUES', 'SCIENCE_AND_TECHNOLOGY', 'ENTERTAINMENT_AND_MEDIA', 'SPORTS_AND_LEISURE');
ALTER TABLE "Category" ALTER COLUMN "name" TYPE "CategoryEnum_new" USING ("name"::text::"CategoryEnum_new");
ALTER TABLE "Debate_room_Category" ALTER COLUMN "category" TYPE "CategoryEnum_new" USING ("category"::text::"CategoryEnum_new");
ALTER TYPE "CategoryEnum" RENAME TO "CategoryEnum_old";
ALTER TYPE "CategoryEnum_new" RENAME TO "CategoryEnum";
DROP TYPE "CategoryEnum_old";
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "InterestEnum_new" AS ENUM ('ELECTIONS', 'GOVERNMENT_POLICY', 'INTERNATIONAL_RELATIONS', 'POLITICAL_STRATEGIES', 'ECONOMY', 'BUSINESS_TRENDS', 'GLOBAL_TRADE', 'INNOVATION_IN_BUSINESS', 'LEGAL_SYSTEM', 'CRIMINAL_JUSTICE', 'CIVIL_RIGHTS', 'COURT_DECISIONS', 'EDUCATIONAL_POLICY', 'LEARNING_TECHNIQUES', 'SCHOOL_REFORMS', 'CLIMATE_CHANGE', 'ENVIRONMENTAL_POLICY', 'SUSTAINABLE_LIVING', 'RENEWABLE_ENERGY', 'SOCIAL_EQUALITY', 'COMMUNITY_DEVELOPMENT', 'CULTURAL_DIVERSITY', 'HUMAN_RIGHTS', 'WEB_DEVELOPMENT', 'SOFTWARE_ENGINEERING', 'AI', 'TECH_INNOVATION', 'CYBERSECURITY', 'ROBOTICS', 'DATA_SCIENCE', 'MOBILE_TECHNOLOGY', 'FILM_AND_TV', 'MUSIC', 'JOURNALISM', 'DIGITAL_MEDIA', 'LITERATURE_AND_THEATRE', 'CRICKET', 'IPL', 'WWE', 'SPORTS_GENERAL', 'FITNESS', 'FOOTBALL', 'BASKETBALL', 'TENNIS', 'FORMULA_ONE');
ALTER TABLE "User" ALTER COLUMN "blocked_intrests" TYPE "InterestEnum_new"[] USING ("blocked_intrests"::text::"InterestEnum_new"[]);
ALTER TABLE "Interest" ALTER COLUMN "name" TYPE "InterestEnum_new" USING ("name"::text::"InterestEnum_new");
ALTER TABLE "Debate_room" ALTER COLUMN "sub_categories" TYPE "InterestEnum_new"[] USING ("sub_categories"::text::"InterestEnum_new"[]);
ALTER TYPE "InterestEnum" RENAME TO "InterestEnum_old";
ALTER TYPE "InterestEnum_new" RENAME TO "InterestEnum";
DROP TYPE "InterestEnum_old";
COMMIT;
