// Define global category enum
export enum CategoryEnum {
  POLITICS_AND_GOVERNANCE = 'POLITICS_AND_GOVERNANCE',
  ECONOMY_AND_DEVELOPMENT = 'ECONOMY_AND_DEVELOPMENT',
  LAW_AND_JUSTICE = 'LAW_AND_JUSTICE',
  EDUCATION = 'EDUCATION',
  ENVIRONMENT_AND_SUSTAINABILITY = 'ENVIRONMENT_AND_SUSTAINABILITY',
  SOCIAL_ISSUES = 'SOCIAL_ISSUES',
  HEALTH_AND_WELLNESS = 'HEALTH_AND_WELLNESS',
  SCIENCE_AND_TECHNOLOGY = 'SCIENCE_AND_TECHNOLOGY',
  ENTERTAINMENT_AND_MEDIA = 'ENTERTAINMENT_AND_MEDIA',
  SPORTS_AND_LEISURE = 'SPORTS_AND_LEISURE',
}

// Define subcategory enums for each category
export enum PoliticsGovernanceInterest {
  ELECTIONS = 'ELECTIONS',
  POLITICAL_PARTIES = 'POLITICAL_PARTIES',
  GOVERNMENT_POLICIES = 'GOVERNMENT_POLICIES',
  CORRUPTION = 'CORRUPTION',
  INTERNATIONAL_RELATIONS = 'INTERNATIONAL_RELATIONS',
}

export enum EconomyDevelopmentInterest {
  JOBS_AND_EMPLOYMENT = 'JOBS_AND_EMPLOYMENT',
  ECONOMIC_POLICIES = 'ECONOMIC_POLICIES',
  INCOME_INEQUALITY = 'INCOME_INEQUALITY',
  TRADE_AND_COMMERCE = 'TRADE_AND_COMMERCE',
  TAXATION = 'TAXATION',
}

export enum LawJusticeInterest {
  CRIME_AND_PUNISHMENT = 'CRIME_AND_PUNISHMENT',
  LEGAL_REFORMS = 'LEGAL_REFORMS',
  JUSTICE_SYSTEM = 'JUSTICE_SYSTEM',
  POLICING = 'POLICING',
  CYBERCRIME = 'CYBERCRIME',
}

export enum EducationInterest {
  SCHOOL_REFORMS = 'SCHOOL_REFORMS',
  HIGHER_EDUCATION = 'HIGHER_EDUCATION',
  ONLINE_LEARNING = 'ONLINE_LEARNING',
  EDUCATION_POLICIES = 'EDUCATION_POLICIES',
  STUDENT_WELFARE = 'STUDENT_WELFARE',
}

export enum EnvironmentSustainabilityInterest {
  CLIMATE_CHANGE = 'CLIMATE_CHANGE',
  POLLUTION = 'POLLUTION',
  RENEWABLE_ENERGY = 'RENEWABLE_ENERGY',
  WILDLIFE_CONSERVATION = 'WILDLIFE_CONSERVATION',
  WASTE_MANAGEMENT = 'WASTE_MANAGEMENT',
}

export enum SocialIssuesInterest {
  CASTE_SYSTEM = 'CASTE_SYSTEM',
  GENDER_EQUALITY = 'GENDER_EQUALITY',
  MINORITY_RIGHTS = 'MINORITY_RIGHTS',
  POVERTY = 'POVERTY',
  HUMAN_RIGHTS = 'HUMAN_RIGHTS',
  LGBTQ_PLUS_RIGHTS = 'LGBTQ_PLUS_RIGHTS',
}

export enum HealthWellnessInterest {
  PUBLIC_HEALTH = 'PUBLIC_HEALTH',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  HEALTHCARE_ACCESS = 'HEALTHCARE_ACCESS',
  NUTRITION = 'NUTRITION',
  DISEASE_PREVENTION = 'DISEASE_PREVENTION',
  MEDICAL_ETHICS = 'MEDICAL_ETHICS',
}

export enum ScienceTechnologyInterest {
  ARTIFICIAL_INTELLIGENCE = 'ARTIFICIAL_INTELLIGENCE',
  SPACE_EXPLORATION = 'SPACE_EXPLORATION',
  MEDICAL_SCIENCE = 'MEDICAL_SCIENCE',
  ROBOTICS = 'ROBOTICS',
  INFORMATION_TECHNOLOGY = 'INFORMATION_TECHNOLOGY',
  ENVIRONMENTAL_TECH = 'ENVIRONMENTAL_TECH',
}

export enum EntertainmentMediaInterest {
  HOLLYWOOD = 'HOLLYWOOD',
  BOLLYWOOD = 'BOLLYWOOD',
  TV_SHOWS = 'TV_SHOWS',
  MUSIC = 'MUSIC',
  GAMING = 'GAMING',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  CENSORSHIP = 'CENSORSHIP',
}

export enum SportsLeisureInterest {
  CRICKET = 'CRICKET',
  FOOTBALL = 'FOOTBALL',
  HOCKEY = 'HOCKEY',
  TENNIS = 'TENNIS',
  BASKETBALL = 'BASKETBALL',
  MOTORSPORTS = 'MOTORSPORTS',
}
